CREATE TABLE tms_organizations (
  org_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_code VARCHAR2(50) NOT NULL UNIQUE,
  org_name VARCHAR2(200) NOT NULL,
  parent_org_id NUMBER,
  status VARCHAR2(20) NOT NULL CHECK (status IN ('ACTIVE','SUSPENDED','ONBOARDING')),
  org_type VARCHAR2(50) NOT NULL,
  can_view_child_data CHAR(1) DEFAULT 'N' NOT NULL CHECK (can_view_child_data IN ('Y','N')),
  created_by VARCHAR2(255) NOT NULL,
  created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_by VARCHAR2(255),
  updated_date TIMESTAMP,
  record_version NUMBER DEFAULT 1 NOT NULL,
  CONSTRAINT fk_org_parent FOREIGN KEY (parent_org_id) REFERENCES tms_organizations(org_id)
);

CREATE TABLE tms_departments (
  department_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id NUMBER NOT NULL,
  department_code VARCHAR2(50) NOT NULL,
  department_name VARCHAR2(200) NOT NULL,
  status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL CHECK (status IN ('ACTIVE','INACTIVE')),
  created_by VARCHAR2(255) NOT NULL,
  created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_by VARCHAR2(255),
  updated_date TIMESTAMP,
  record_version NUMBER DEFAULT 1 NOT NULL,
  CONSTRAINT fk_dept_org FOREIGN KEY (org_id) REFERENCES tms_organizations(org_id),
  CONSTRAINT uq_dept_org_code UNIQUE (org_id, department_code)
);

CREATE TABLE tms_cost_centres (
  cost_centre_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id NUMBER NOT NULL,
  department_id NUMBER,
  cost_centre_code VARCHAR2(50) NOT NULL,
  cost_centre_name VARCHAR2(200) NOT NULL,
  status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL CHECK (status IN ('ACTIVE','INACTIVE')),
  created_by VARCHAR2(255) NOT NULL,
  created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_by VARCHAR2(255),
  updated_date TIMESTAMP,
  record_version NUMBER DEFAULT 1 NOT NULL,
  CONSTRAINT fk_cc_org FOREIGN KEY (org_id) REFERENCES tms_organizations(org_id),
  CONSTRAINT fk_cc_dept FOREIGN KEY (department_id) REFERENCES tms_departments(department_id),
  CONSTRAINT uq_cc_org_code UNIQUE (org_id, cost_centre_code)
);

CREATE TABLE tms_users (
  user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login_name VARCHAR2(255) NOT NULL UNIQUE,
  external_identity VARCHAR2(500),
  account_status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL CHECK (account_status IN ('ACTIVE','INACTIVE','LOCKED')),
  created_by VARCHAR2(255) NOT NULL,
  created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_by VARCHAR2(255),
  updated_date TIMESTAMP,
  record_version NUMBER DEFAULT 1 NOT NULL
);

CREATE TABLE tms_user_details (
  user_id NUMBER PRIMARY KEY,
  full_name VARCHAR2(300) NOT NULL,
  employee_code VARCHAR2(100),
  email VARCHAR2(320),
  phone VARCHAR2(100),
  created_by VARCHAR2(255) NOT NULL,
  created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_by VARCHAR2(255),
  updated_date TIMESTAMP,
  record_version NUMBER DEFAULT 1 NOT NULL,
  CONSTRAINT fk_ud_user FOREIGN KEY (user_id) REFERENCES tms_users(user_id)
);
