CREATE TABLE tms_roles (
  role_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id NUMBER,
  role_code VARCHAR2(100) NOT NULL,
  role_name VARCHAR2(200) NOT NULL,
  status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL CHECK (status IN ('ACTIVE','INACTIVE')),
  created_by VARCHAR2(255) NOT NULL,
  created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_by VARCHAR2(255),
  updated_date TIMESTAMP,
  record_version NUMBER DEFAULT 1 NOT NULL,
  CONSTRAINT fk_role_org FOREIGN KEY (org_id) REFERENCES tms_organizations(org_id),
  CONSTRAINT uq_role_code_org UNIQUE (org_id, role_code)
);

CREATE TABLE tms_role_details (
  role_id NUMBER PRIMARY KEY,
  role_description VARCHAR2(2000),
  role_category VARCHAR2(100),
  is_system_role CHAR(1) DEFAULT 'N' NOT NULL CHECK (is_system_role IN ('Y','N')),
  created_by VARCHAR2(255) NOT NULL,
  created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_by VARCHAR2(255),
  updated_date TIMESTAMP,
  record_version NUMBER DEFAULT 1 NOT NULL,
  CONSTRAINT fk_rd_role FOREIGN KEY (role_id) REFERENCES tms_roles(role_id)
);

CREATE TABLE tms_functions (
  function_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  function_code VARCHAR2(100) NOT NULL UNIQUE,
  function_name VARCHAR2(200) NOT NULL,
  created_by VARCHAR2(255) NOT NULL,
  created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_by VARCHAR2(255),
  updated_date TIMESTAMP,
  record_version NUMBER DEFAULT 1 NOT NULL
);

CREATE TABLE tms_actions (
  action_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action_code VARCHAR2(100) NOT NULL UNIQUE,
  action_name VARCHAR2(200) NOT NULL,
  created_by VARCHAR2(255) NOT NULL,
  created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_by VARCHAR2(255),
  updated_date TIMESTAMP,
  record_version NUMBER DEFAULT 1 NOT NULL
);

CREATE TABLE tms_permissions (
  permission_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  function_id NUMBER NOT NULL,
  action_id NUMBER NOT NULL,
  permission_code VARCHAR2(220) NOT NULL UNIQUE,
  created_by VARCHAR2(255) NOT NULL,
  created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_by VARCHAR2(255),
  updated_date TIMESTAMP,
  record_version NUMBER DEFAULT 1 NOT NULL,
  CONSTRAINT fk_perm_fn FOREIGN KEY (function_id) REFERENCES tms_functions(function_id),
  CONSTRAINT fk_perm_act FOREIGN KEY (action_id) REFERENCES tms_actions(action_id),
  CONSTRAINT uq_perm_fn_action UNIQUE (function_id, action_id)
);

CREATE TABLE tms_role_permissions (
  role_id NUMBER NOT NULL,
  permission_id NUMBER NOT NULL,
  created_by VARCHAR2(255) NOT NULL,
  created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  PRIMARY KEY (role_id, permission_id),
  CONSTRAINT fk_rp_role FOREIGN KEY (role_id) REFERENCES tms_roles(role_id),
  CONSTRAINT fk_rp_perm FOREIGN KEY (permission_id) REFERENCES tms_permissions(permission_id)
);

CREATE TABLE tms_user_organizations (
  user_org_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL,
  org_id NUMBER NOT NULL,
  department_id NUMBER,
  is_primary CHAR(1) DEFAULT 'N' NOT NULL CHECK (is_primary IN ('Y','N')),
  membership_status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL CHECK (membership_status IN ('ACTIVE','INACTIVE','SUSPENDED')),
  effective_from DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
  effective_to DATE,
  created_by VARCHAR2(255) NOT NULL,
  created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_by VARCHAR2(255),
  updated_date TIMESTAMP,
  record_version NUMBER DEFAULT 1 NOT NULL,
  CONSTRAINT fk_uo_user FOREIGN KEY (user_id) REFERENCES tms_users(user_id),
  CONSTRAINT fk_uo_org FOREIGN KEY (org_id) REFERENCES tms_organizations(org_id),
  CONSTRAINT fk_uo_dept FOREIGN KEY (department_id) REFERENCES tms_departments(department_id)
);

CREATE TABLE tms_user_organization_roles (
  user_org_role_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_org_id NUMBER NOT NULL,
  role_id NUMBER NOT NULL,
  effective_from DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
  effective_to DATE,
  status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL CHECK (status IN ('ACTIVE','INACTIVE')),
  created_by VARCHAR2(255) NOT NULL,
  created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_by VARCHAR2(255),
  updated_date TIMESTAMP,
  record_version NUMBER DEFAULT 1 NOT NULL,
  CONSTRAINT fk_uor_membership FOREIGN KEY (user_org_id) REFERENCES tms_user_organizations(user_org_id),
  CONSTRAINT fk_uor_role FOREIGN KEY (role_id) REFERENCES tms_roles(role_id),
  CONSTRAINT uq_uor UNIQUE (user_org_id, role_id)
);

CREATE TABLE tms_delegations (
  delegation_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  delegator_user_id NUMBER NOT NULL,
  delegate_user_id NUMBER NOT NULL,
  org_id NUMBER NOT NULL,
  role_id NUMBER,
  start_date TIMESTAMP NOT NULL,
  end_date TIMESTAMP NOT NULL,
  status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL CHECK (status IN ('ACTIVE','EXPIRED','CANCELLED')),
  reason VARCHAR2(2000),
  created_by VARCHAR2(255) NOT NULL,
  created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_by VARCHAR2(255),
  updated_date TIMESTAMP,
  record_version NUMBER DEFAULT 1 NOT NULL,
  CONSTRAINT fk_del_delegator FOREIGN KEY (delegator_user_id) REFERENCES tms_users(user_id),
  CONSTRAINT fk_del_delegate FOREIGN KEY (delegate_user_id) REFERENCES tms_users(user_id),
  CONSTRAINT fk_del_org FOREIGN KEY (org_id) REFERENCES tms_organizations(org_id),
  CONSTRAINT fk_del_role FOREIGN KEY (role_id) REFERENCES tms_roles(role_id),
  CONSTRAINT ck_del_dates CHECK (end_date > start_date)
);

CREATE TABLE tms_categories (
  category_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id NUMBER,
  category_code VARCHAR2(100) NOT NULL,
  category_name VARCHAR2(200) NOT NULL,
  status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL CHECK (status IN ('ACTIVE','INACTIVE')),
  created_by VARCHAR2(255) NOT NULL,
  created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_by VARCHAR2(255),
  updated_date TIMESTAMP,
  record_version NUMBER DEFAULT 1 NOT NULL,
  CONSTRAINT fk_cat_org FOREIGN KEY (org_id) REFERENCES tms_organizations(org_id)
);

CREATE TABLE tms_status_transitions (
  transition_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_status VARCHAR2(30) NOT NULL,
  to_status VARCHAR2(30) NOT NULL,
  required_function_code VARCHAR2(100) NOT NULL,
  required_action_code VARCHAR2(100) NOT NULL,
  created_by VARCHAR2(255) NOT NULL,
  created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_by VARCHAR2(255),
  updated_date TIMESTAMP,
  record_version NUMBER DEFAULT 1 NOT NULL,
  CONSTRAINT uq_status_transition UNIQUE (from_status,to_status)
);

CREATE TABLE tms_workflow_rules (
  workflow_rule_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id NUMBER,
  category_id NUMBER,
  priority VARCHAR2(20),
  rule_name VARCHAR2(200) NOT NULL,
  rule_type VARCHAR2(50) NOT NULL,
  rule_definition CLOB,
  status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  created_by VARCHAR2(255) NOT NULL,
  created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_by VARCHAR2(255),
  updated_date TIMESTAMP,
  record_version NUMBER DEFAULT 1 NOT NULL,
  CONSTRAINT fk_wr_org FOREIGN KEY (org_id) REFERENCES tms_organizations(org_id),
  CONSTRAINT fk_wr_cat FOREIGN KEY (category_id) REFERENCES tms_categories(category_id)
);
