/* ================================================================
   TMS SECURITY AND REFERENCE TABLES
   Blueprint Version : v1.5

   IMPORTANT BUSINESS RULES
   ----------------------------------------------------------------
   1. Super User Organization is a dedicated platform organization.
   2. Users associated with the Super User Organization may have
      multiple organization memberships.
   3. Normal customer-organization users may belong to only one
      organization.
   4. Organization membership and role assignment remain separate.
   5. Super User authority is NOT represented by a permission.
   6. TMS_ROLE_DETAILS.IS_SYSTEM_ROLE identifies system roles.
   7. Data integrity and business rules remain applicable to
      Super User.
   ================================================================ */


/* ================================================================
   1. ROLES
   ================================================================ */

CREATE TABLE tms_roles (
  role_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id NUMBER,
  role_code VARCHAR2(100) NOT NULL,
  role_name VARCHAR2(200) NOT NULL,
  status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL
      CHECK (status IN ('ACTIVE','INACTIVE')),
  created_by VARCHAR2(255) NOT NULL,
  created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_by VARCHAR2(255),
  updated_date TIMESTAMP,
  record_version NUMBER DEFAULT 1 NOT NULL,

  CONSTRAINT fk_role_org
      FOREIGN KEY (org_id)
      REFERENCES tms_organizations(org_id),

  CONSTRAINT uq_role_code_org
      UNIQUE (org_id, role_code)
);


/* ================================================================
   2. ROLE DETAILS
   ================================================================ */

CREATE TABLE tms_role_details (
  role_id NUMBER PRIMARY KEY,
  role_description VARCHAR2(2000),
  role_category VARCHAR2(100),
  is_system_role CHAR(1) DEFAULT 'N' NOT NULL
      CHECK (is_system_role IN ('Y','N')),
  created_by VARCHAR2(255) NOT NULL,
  created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_by VARCHAR2(255),
  updated_date TIMESTAMP,
  record_version NUMBER DEFAULT 1 NOT NULL,

  CONSTRAINT fk_rd_role
      FOREIGN KEY (role_id)
      REFERENCES tms_roles(role_id)
);


/* ================================================================
   3. FUNCTIONS
   ================================================================ */

CREATE TABLE tms_functions (
  function_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  function_code VARCHAR2(100) NOT NULL UNIQUE,
  function_name VARCHAR2(200) NOT NULL,
  created_by VARCHAR2(255) NOT NULL,
  created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_by VARCHAR2(255),
  updated_date TIMESTAMP,
  record_version NUMBER DEFAULT 1 NOT NULL
);


/* ================================================================
   4. ACTIONS
   ================================================================ */

CREATE TABLE tms_actions (
  action_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action_code VARCHAR2(100) NOT NULL UNIQUE,
  action_name VARCHAR2(200) NOT NULL,
  created_by VARCHAR2(255) NOT NULL,
  created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_by VARCHAR2(255),
  updated_date TIMESTAMP,
  record_version NUMBER DEFAULT 1 NOT NULL
);


/* ================================================================
   5. PERMISSIONS
   ================================================================ */

CREATE TABLE tms_permissions (
  permission_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  function_id NUMBER NOT NULL,
  action_id NUMBER NOT NULL,
  permission_code VARCHAR2(220) NOT NULL UNIQUE,
  created_by VARCHAR2(255) NOT NULL,
  created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_by VARCHAR2(255),
  updated_date TIMESTAMP,
  record_version NUMBER DEFAULT 1 NOT NULL,

  CONSTRAINT fk_perm_fn
      FOREIGN KEY (function_id)
      REFERENCES tms_functions(function_id),

  CONSTRAINT fk_perm_act
      FOREIGN KEY (action_id)
      REFERENCES tms_actions(action_id),

  CONSTRAINT uq_perm_fn_action
      UNIQUE (function_id, action_id)
);


/* ================================================================
   6. ROLE PERMISSIONS
   ================================================================ */

CREATE TABLE tms_role_permissions (
  role_id NUMBER NOT NULL,
  permission_id NUMBER NOT NULL,
  created_by VARCHAR2(255) NOT NULL,
  created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

  PRIMARY KEY (role_id, permission_id),

  CONSTRAINT fk_rp_role
      FOREIGN KEY (role_id)
      REFERENCES tms_roles(role_id),

  CONSTRAINT fk_rp_perm
      FOREIGN KEY (permission_id)
      REFERENCES tms_permissions(permission_id)
);


/* ================================================================
   7. USER ORGANIZATIONS
   ----------------------------------------------------------------
   This table represents:
       USER <-> ORGANIZATION <-> DEPARTMENT

   Multiple memberships are allowed structurally because the
   Super User Organization model requires them.

   Business restriction is enforced below:
       - Super User Organization users -> multiple organizations
       - Normal customer users         -> one organization
   ================================================================ */

CREATE TABLE tms_user_organizations (
  user_org_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL,
  org_id NUMBER NOT NULL,
  department_id NUMBER,
  is_primary CHAR(1) DEFAULT 'N' NOT NULL
      CHECK (is_primary IN ('Y','N')),
  membership_status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL
      CHECK (membership_status IN ('ACTIVE','INACTIVE','SUSPENDED')),
  effective_from DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
  effective_to DATE,
  created_by VARCHAR2(255) NOT NULL,
  created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_by VARCHAR2(255),
  updated_date TIMESTAMP,
  record_version NUMBER DEFAULT 1 NOT NULL,

  CONSTRAINT fk_uo_user
      FOREIGN KEY (user_id)
      REFERENCES tms_users(user_id),

  CONSTRAINT fk_uo_org
      FOREIGN KEY (org_id)
      REFERENCES tms_organizations(org_id),

  CONSTRAINT fk_uo_dept
      FOREIGN KEY (department_id)
      REFERENCES tms_departments(department_id)
);


/* ================================================================
   8. USER ORGANIZATION ROLES
   ================================================================ */

CREATE TABLE tms_user_organization_roles (
  user_org_role_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_org_id NUMBER NOT NULL,
  role_id NUMBER NOT NULL,
  effective_from DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
  effective_to DATE,
  status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL
      CHECK (status IN ('ACTIVE','INACTIVE')),
  created_by VARCHAR2(255) NOT NULL,
  created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_by VARCHAR2(255),
  updated_date TIMESTAMP,
  record_version NUMBER DEFAULT 1 NOT NULL,

  CONSTRAINT fk_uor_membership
      FOREIGN KEY (user_org_id)
      REFERENCES tms_user_organizations(user_org_id),

  CONSTRAINT fk_uor_role
      FOREIGN KEY (role_id)
      REFERENCES tms_roles(role_id),

  CONSTRAINT uq_uor
      UNIQUE (user_org_id, role_id)
);


/* ================================================================
   9. DELEGATIONS
   ================================================================ */

CREATE TABLE tms_delegations (
  delegation_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  delegator_user_id NUMBER NOT NULL,
  delegate_user_id NUMBER NOT NULL,
  org_id NUMBER NOT NULL,
  role_id NUMBER,
  start_date TIMESTAMP NOT NULL,
  end_date TIMESTAMP NOT NULL,
  status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL
      CHECK (status IN ('ACTIVE','EXPIRED','CANCELLED')),
  reason VARCHAR2(2000),
  created_by VARCHAR2(255) NOT NULL,
  created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_by VARCHAR2(255),
  updated_date TIMESTAMP,
  record_version NUMBER DEFAULT 1 NOT NULL,

  CONSTRAINT fk_del_delegator
      FOREIGN KEY (delegator_user_id)
      REFERENCES tms_users(user_id),

  CONSTRAINT fk_del_delegate
      FOREIGN KEY (delegate_user_id)
      REFERENCES tms_users(user_id),

  CONSTRAINT fk_del_org
      FOREIGN KEY (org_id)
      REFERENCES tms_organizations(org_id),

  CONSTRAINT fk_del_role
      FOREIGN KEY (role_id)
      REFERENCES tms_roles(role_id),

  CONSTRAINT ck_del_dates
      CHECK (end_date > start_date)
);


/* ================================================================
   10. CATEGORIES
   ================================================================ */

CREATE TABLE tms_categories (
  category_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id NUMBER,
  category_code VARCHAR2(100) NOT NULL,
  category_name VARCHAR2(200) NOT NULL,
  status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL
      CHECK (status IN ('ACTIVE','INACTIVE')),
  created_by VARCHAR2(255) NOT NULL,
  created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_by VARCHAR2(255),
  updated_date TIMESTAMP,
  record_version NUMBER DEFAULT 1 NOT NULL,

  CONSTRAINT fk_cat_org
      FOREIGN KEY (org_id)
      REFERENCES tms_organizations(org_id)
);


/* ================================================================
   11. STATUS TRANSITIONS
   ================================================================ */

CREATE TABLE tms_status_transitions (
  transition_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  from_status VARCHAR2(30) NOT NULL,
  to_status VARCHAR2(30) NOT NULL,
  required_function_code VARCHAR2(100) NOT NULL,
  required_action_code VARCHAR2(100) NOT NULL,
  created_by VARCHAR2(255) NOT NULL,
  created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_by VARCHAR2(255),
  updated_date TIMESTAMP,
  record_version NUMBER DEFAULT 1 NOT NULL,

  CONSTRAINT uq_status_transition
      UNIQUE (from_status, to_status)
);


/* ================================================================
   12. WORKFLOW RULES
   ================================================================ */

CREATE TABLE tms_workflow_rules (
  workflow_rule_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id NUMBER,
  category_id NUMBER,
  priority VARCHAR2(20),
  rule_name VARCHAR2(200) NOT NULL,
  rule_type VARCHAR2(50) NOT NULL,
  rule_definition CLOB,
  status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  created_by VARCHAR2(255) NOT NULL,
  created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_by VARCHAR2(255),
  updated_date TIMESTAMP,
  record_version NUMBER DEFAULT 1 NOT NULL,

  CONSTRAINT fk_wr_org
      FOREIGN KEY (org_id)
      REFERENCES tms_organizations(org_id),

  CONSTRAINT fk_wr_cat
      FOREIGN KEY (category_id)
      REFERENCES tms_categories(category_id)
);


/* ================================================================
   13. DUPLICATE USER / ORGANIZATION MEMBERSHIP PREVENTION
   ----------------------------------------------------------------
   A user must not have two membership rows for the same
   organization.
   ================================================================ */

CREATE UNIQUE INDEX uq_tms_user_org_membership
    ON tms_user_organizations (
        user_id,
        org_id
    );


/* ================================================================
   14. ONE PRIMARY ORGANIZATION PER USER
   ----------------------------------------------------------------
   Oracle NULL behavior allows the following design:

       is_primary = 'Y'
           -> only one row per user

       is_primary = 'N'
           -> unlimited rows

   This supports multiple memberships while preserving exactly
   one primary membership.
   ================================================================ */

CREATE UNIQUE INDEX uq_tms_user_primary_org
    ON tms_user_organizations (
        CASE
            WHEN is_primary = 'Y'
            THEN user_id
        END
    );


/* ================================================================
   15. EFFECTIVE DATE VALIDATION
   ================================================================ */

ALTER TABLE tms_user_organizations
ADD CONSTRAINT ck_uo_dates
CHECK (
       effective_to IS NULL
       OR effective_to >= effective_from
);


/* ================================================================
   16. ORGANIZATION MEMBERSHIP CONTROL
   ----------------------------------------------------------------
   BUSINESS RULE:

   A user may have multiple organization memberships ONLY when
   the user is associated with the dedicated Super User
   Organization.

   The Super User Organization is identified by:

       ORG_TYPE = 'SUPER_USER'

   This avoids depending on an identity-generated ORG_ID.

   Examples:

       Normal customer user
           Org A -> allowed
           Org B -> rejected

       Super User Organization user
           Super User Org -> allowed
           Customer A     -> allowed
           Customer B     -> allowed
           Customer C     -> allowed
   ================================================================ */

CREATE OR REPLACE TRIGGER trg_tms_user_org_membership
FOR INSERT OR UPDATE OF user_id, org_id, membership_status
ON tms_user_organizations
COMPOUND TRIGGER

    TYPE t_user_id_list IS TABLE OF NUMBER
        INDEX BY VARCHAR2(100);

    G_USER_IDS t_user_id_list;


    AFTER EACH ROW IS
    BEGIN

        G_USER_IDS(TO_CHAR(:NEW.user_id)) := :NEW.user_id;

    END AFTER EACH ROW;


    AFTER STATEMENT IS

        L_USER_ID               NUMBER;
        L_ORG_COUNT             NUMBER;
        L_SUPER_USER_ORG_COUNT  NUMBER;

    BEGIN

        L_USER_ID := G_USER_IDS.FIRST;

        WHILE L_USER_ID IS NOT NULL LOOP

            /* --------------------------------------------------------
               Count active/suspended organizations for this user.

               INACTIVE memberships do not count as current
               organization memberships.
               -------------------------------------------------------- */

            SELECT COUNT(DISTINCT UO.ORG_ID)
              INTO L_ORG_COUNT
              FROM TMS_USER_ORGANIZATIONS UO
             WHERE UO.USER_ID = G_USER_IDS(L_USER_ID)
               AND UO.MEMBERSHIP_STATUS IN ('ACTIVE','SUSPENDED');


            /* --------------------------------------------------------
               Determine whether this user is linked with the
               dedicated Super User Organization.

               ORG_TYPE is used rather than ORG_ID.
               -------------------------------------------------------- */

            SELECT COUNT(*)
              INTO L_SUPER_USER_ORG_COUNT
              FROM TMS_USER_ORGANIZATIONS UO
                   JOIN TMS_ORGANIZATIONS O
                     ON O.ORG_ID = UO.ORG_ID
             WHERE UO.USER_ID = G_USER_IDS(L_USER_ID)
               AND UO.MEMBERSHIP_STATUS IN ('ACTIVE','SUSPENDED')
               AND O.ORG_TYPE = 'SUPER_USER';


            /* --------------------------------------------------------
               Normal customer user:

               Maximum one organization.
               -------------------------------------------------------- */

            IF L_SUPER_USER_ORG_COUNT = 0
               AND L_ORG_COUNT > 1
            THEN

                RAISE_APPLICATION_ERROR(
                    -20021,
                    'TMS-SECURITY-021: A customer organization user '
                    || 'may belong to only one organization.'
                );

            END IF;


            L_USER_ID := G_USER_IDS.NEXT(L_USER_ID);

        END LOOP;

    END AFTER STATEMENT;

END trg_tms_user_org_membership;
/


/* ================================================================
   17. ORGANIZATION / DEPARTMENT CONSISTENCY
   ----------------------------------------------------------------
   A membership department must belong to the same organization
   as the membership.
   ================================================================ */

CREATE OR REPLACE TRIGGER trg_tms_user_org_department
BEFORE INSERT OR UPDATE OF org_id, department_id
ON tms_user_organizations
FOR EACH ROW
DECLARE

    L_COUNT NUMBER;

BEGIN

    IF :NEW.department_id IS NULL THEN
        RETURN;
    END IF;


    SELECT COUNT(*)
      INTO L_COUNT
      FROM TMS_DEPARTMENTS D
     WHERE D.DEPARTMENT_ID = :NEW.DEPARTMENT_ID
       AND D.ORG_ID = :NEW.ORG_ID;


    IF L_COUNT = 0 THEN

        RAISE_APPLICATION_ERROR(
            -20022,
            'TMS-SECURITY-022: Department does not belong '
            || 'to the selected organization.'
        );

    END IF;

END trg_tms_user_org_department;
/


/* ================================================================
   18. ROLE / ORGANIZATION CONSISTENCY
   ----------------------------------------------------------------
   A role attached to a membership must either be:

       1. Global      -> TMS_ROLES.ORG_ID IS NULL

   OR

       2. Same organization as the membership.

   This prevents a role belonging to Organization A from being
   assigned to a user membership belonging to Organization B.
   ================================================================ */

CREATE OR REPLACE TRIGGER trg_tms_user_org_role_scope
BEFORE INSERT OR UPDATE OF user_org_id, role_id
ON tms_user_organization_roles
FOR EACH ROW
DECLARE

    L_MEMBERSHIP_ORG_ID NUMBER;
    L_ROLE_ORG_ID       NUMBER;

BEGIN

    SELECT ORG_ID
      INTO L_MEMBERSHIP_ORG_ID
      FROM TMS_USER_ORGANIZATIONS
     WHERE USER_ORG_ID = :NEW.USER_ORG_ID;


    SELECT ORG_ID
      INTO L_ROLE_ORG_ID
      FROM TMS_ROLES
     WHERE ROLE_ID = :NEW.ROLE_ID;


    IF L_ROLE_ORG_ID IS NOT NULL
       AND L_ROLE_ORG_ID <> L_MEMBERSHIP_ORG_ID
    THEN

        RAISE_APPLICATION_ERROR(
            -20023,
            'TMS-SECURITY-023: Organization-specific role '
            || 'cannot be assigned outside its organization.'
        );

    END IF;

END trg_tms_user_org_role_scope;
/


/* ================================================================
   19. ROLE EFFECTIVE DATE VALIDATION
   ================================================================ */

ALTER TABLE tms_user_organization_roles
ADD CONSTRAINT ck_uor_dates
CHECK (
       effective_to IS NULL
       OR effective_to >= effective_from
);


/* ================================================================
   20. DELEGATION SCOPE VALIDATION
   ----------------------------------------------------------------
   Delegation must remain inside the organization.

   Both delegator and delegate must have an active membership in
   the delegated organization.
   ================================================================ */

CREATE OR REPLACE TRIGGER trg_tms_delegation_scope
BEFORE INSERT OR UPDATE OF
    delegator_user_id,
    delegate_user_id,
    org_id
ON tms_delegations
FOR EACH ROW
DECLARE

    L_COUNT NUMBER;

BEGIN

    /* ------------------------------------------------------------
       Delegator membership
       ------------------------------------------------------------ */

    SELECT COUNT(*)
      INTO L_COUNT
      FROM TMS_USER_ORGANIZATIONS UO
     WHERE UO.USER_ID = :NEW.DELEGATOR_USER_ID
       AND UO.ORG_ID = :NEW.ORG_ID
       AND UO.MEMBERSHIP_STATUS = 'ACTIVE';


    IF L_COUNT = 0 THEN

        RAISE_APPLICATION_ERROR(
            -20024,
            'TMS-SECURITY-024: Delegator is not an active member '
            || 'of the delegated organization.'
        );

    END IF;


    /* ------------------------------------------------------------
       Delegate membership
       ------------------------------------------------------------ */

    SELECT COUNT(*)
      INTO L_COUNT
      FROM TMS_USER_ORGANIZATIONS UO
     WHERE UO.USER_ID = :NEW.DELEGATE_USER_ID
       AND UO.ORG_ID = :NEW.ORG_ID
       AND UO.MEMBERSHIP_STATUS = 'ACTIVE';


    IF L_COUNT = 0 THEN

        RAISE_APPLICATION_ERROR(
            -20025,
            'TMS-SECURITY-025: Delegate is not an active member '
            || 'of the delegated organization.'
        );

    END IF;


    /* ------------------------------------------------------------
       Delegation role must be global or belong to the same
       organization.
       ------------------------------------------------------------ */

    IF :NEW.ROLE_ID IS NOT NULL THEN

        SELECT COUNT(*)
          INTO L_COUNT
          FROM TMS_ROLES R
         WHERE R.ROLE_ID = :NEW.ROLE_ID
           AND (
                  R.ORG_ID IS NULL
                  OR R.ORG_ID = :NEW.ORG_ID
               );


        IF L_COUNT = 0 THEN

            RAISE_APPLICATION_ERROR(
                -20026,
                'TMS-SECURITY-026: Delegated role is outside '
                || 'the organization scope.'
            );

        END IF;

    END IF;

END trg_tms_delegation_scope;
/


/* ================================================================
   21. CATEGORY ORGANIZATION RULE
   ----------------------------------------------------------------
   Global category:
       ORG_ID IS NULL

   Organization category:
       ORG_ID contains owning organization.

   No additional structural restriction required here because
   category scope is resolved by the Data Access layer.
   ================================================================ */


/* ================================================================
   22. REFERENCE TABLE COMPLETION
   ================================================================ */

COMMENT ON TABLE tms_user_organizations IS
'User-to-organization membership. Multiple organizations are permitted only for users associated with the Super User Organization.';

COMMENT ON COLUMN tms_user_organizations.is_primary IS
'Exactly one primary active membership is permitted per user.';

COMMENT ON TABLE tms_user_organization_roles IS
'Roles assigned to an organization membership. Global roles may have ORG_ID NULL; organization roles must match membership organization.';

COMMENT ON COLUMN tms_role_details.is_system_role IS
'Identifies platform/system roles such as SUPER_USER. System-role identity does not itself represent a permission.';


/* ================================================================
   END OF SECURITY / REFERENCE TABLE DEFINITIONS
   ================================================================ */