CREATE TABLE tms_tickets (
  ticket_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id NUMBER NOT NULL,
  category_id NUMBER NOT NULL,
  ticket_ref VARCHAR2(100) NOT NULL UNIQUE,
  subject VARCHAR2(500) NOT NULL,
  description CLOB,
  priority VARCHAR2(20) DEFAULT 'MEDIUM' NOT NULL CHECK (priority IN ('CRITICAL','HIGH','MEDIUM','LOW')),
  status VARCHAR2(30) DEFAULT 'NEW' NOT NULL,
  requester_user_id NUMBER NOT NULL,
  assigned_user_id NUMBER,
  assigned_department_id NUMBER,
  opened_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  resolved_date TIMESTAMP,
  closed_date TIMESTAMP,
  sla_response_due TIMESTAMP,
  sla_resolution_due TIMESTAMP,
  response_breached CHAR(1) DEFAULT 'N' NOT NULL CHECK (response_breached IN ('Y','N')),
  resolution_breached CHAR(1) DEFAULT 'N' NOT NULL CHECK (resolution_breached IN ('Y','N')),
  created_by VARCHAR2(255) NOT NULL,
  created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_by VARCHAR2(255),
  updated_date TIMESTAMP,
  record_version NUMBER DEFAULT 1 NOT NULL,
  CONSTRAINT fk_ticket_org FOREIGN KEY (org_id) REFERENCES tms_organizations(org_id),
  CONSTRAINT fk_ticket_cat FOREIGN KEY (category_id) REFERENCES tms_categories(category_id),
  CONSTRAINT fk_ticket_requester FOREIGN KEY (requester_user_id) REFERENCES tms_users(user_id),
  CONSTRAINT fk_ticket_assignee FOREIGN KEY (assigned_user_id) REFERENCES tms_users(user_id),
  CONSTRAINT fk_ticket_dept FOREIGN KEY (assigned_department_id) REFERENCES tms_departments(department_id)
);

CREATE TABLE tms_ticket_details (
  ticket_detail_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id NUMBER NOT NULL,
  org_id NUMBER NOT NULL,
  detail_json CLOB CHECK (detail_json IS JSON),
  created_by VARCHAR2(255) NOT NULL,
  created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_by VARCHAR2(255),
  updated_date TIMESTAMP,
  record_version NUMBER DEFAULT 1 NOT NULL,
  CONSTRAINT fk_td_ticket FOREIGN KEY (ticket_id) REFERENCES tms_tickets(ticket_id),
  CONSTRAINT fk_td_org FOREIGN KEY (org_id) REFERENCES tms_organizations(org_id)
);

CREATE TABLE tms_ticket_comments (
  comment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id NUMBER NOT NULL,
  org_id NUMBER NOT NULL,
  comment_text CLOB NOT NULL,
  comment_type VARCHAR2(30) DEFAULT 'INTERNAL' NOT NULL,
  created_by VARCHAR2(255) NOT NULL,
  created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_by VARCHAR2(255),
  updated_date TIMESTAMP,
  record_version NUMBER DEFAULT 1 NOT NULL,
  CONSTRAINT fk_tc_ticket FOREIGN KEY (ticket_id) REFERENCES tms_tickets(ticket_id),
  CONSTRAINT fk_tc_org FOREIGN KEY (org_id) REFERENCES tms_organizations(org_id)
);

CREATE TABLE tms_ticket_attachments (
  attachment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id NUMBER NOT NULL,
  org_id NUMBER NOT NULL,
  file_name VARCHAR2(500) NOT NULL,
  mime_type VARCHAR2(255),
  file_size NUMBER,
  storage_reference VARCHAR2(2000) NOT NULL,
  created_by VARCHAR2(255) NOT NULL,
  created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_by VARCHAR2(255),
  updated_date TIMESTAMP,
  record_version NUMBER DEFAULT 1 NOT NULL,
  CONSTRAINT fk_ta_ticket FOREIGN KEY (ticket_id) REFERENCES tms_tickets(ticket_id),
  CONSTRAINT fk_ta_org FOREIGN KEY (org_id) REFERENCES tms_organizations(org_id)
);

CREATE TABLE tms_ticket_history (
  history_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id NUMBER NOT NULL,
  org_id NUMBER NOT NULL,
  old_status VARCHAR2(30),
  new_status VARCHAR2(30) NOT NULL,
  actor_user_id NUMBER,
  comment_text VARCHAR2(2000),
  created_by VARCHAR2(255) NOT NULL,
  created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_by VARCHAR2(255),
  updated_date TIMESTAMP,
  record_version NUMBER DEFAULT 1 NOT NULL,
  CONSTRAINT fk_th_ticket FOREIGN KEY (ticket_id) REFERENCES tms_tickets(ticket_id),
  CONSTRAINT fk_th_org FOREIGN KEY (org_id) REFERENCES tms_organizations(org_id),
  CONSTRAINT fk_th_actor FOREIGN KEY (actor_user_id) REFERENCES tms_users(user_id)
);

CREATE TABLE tms_ticket_watchers (
  ticket_watcher_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id NUMBER NOT NULL,
  org_id NUMBER NOT NULL,
  user_id NUMBER NOT NULL,
  created_by VARCHAR2(255) NOT NULL,
  created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_by VARCHAR2(255),
  updated_date TIMESTAMP,
  record_version NUMBER DEFAULT 1 NOT NULL,
  CONSTRAINT fk_tw_ticket FOREIGN KEY (ticket_id) REFERENCES tms_tickets(ticket_id),
  CONSTRAINT fk_tw_org FOREIGN KEY (org_id) REFERENCES tms_organizations(org_id),
  CONSTRAINT fk_tw_user FOREIGN KEY (user_id) REFERENCES tms_users(user_id),
  CONSTRAINT uq_tw UNIQUE(ticket_id,user_id)
);

CREATE TABLE tms_sla_rules (
  sla_rule_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id NUMBER,
  category_id NUMBER,
  priority VARCHAR2(20) NOT NULL,
  response_minutes NUMBER NOT NULL,
  resolution_minutes NUMBER NOT NULL,
  status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  created_by VARCHAR2(255) NOT NULL,
  created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_by VARCHAR2(255),
  updated_date TIMESTAMP,
  record_version NUMBER DEFAULT 1 NOT NULL,
  CONSTRAINT fk_sla_org FOREIGN KEY (org_id) REFERENCES tms_organizations(org_id),
  CONSTRAINT fk_sla_cat FOREIGN KEY (category_id) REFERENCES tms_categories(category_id)
);

CREATE TABLE tms_audit_log (
  audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_name VARCHAR2(128) NOT NULL,
  pk_value VARCHAR2(1000) NOT NULL,
  action_type VARCHAR2(10) NOT NULL CHECK (action_type IN ('INSERT','UPDATE','DELETE')),
  old_value CLOB CHECK (old_value IS JSON),
  new_value CLOB CHECK (new_value IS JSON),
  actor VARCHAR2(255) NOT NULL,
  action_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  session_org_id NUMBER
);

CREATE TABLE tms_notifications_log (
  notification_log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id NUMBER,
  ticket_id NUMBER,
  event_type VARCHAR2(100) NOT NULL,
  recipient VARCHAR2(500) NOT NULL,
  delivery_channel VARCHAR2(30) NOT NULL,
  delivery_status VARCHAR2(30) NOT NULL,
  sent_date TIMESTAMP,
  error_message VARCHAR2(2000),
  created_by VARCHAR2(255) NOT NULL,
  created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_by VARCHAR2(255),
  updated_date TIMESTAMP,
  record_version NUMBER DEFAULT 1 NOT NULL,
  CONSTRAINT fk_nl_org FOREIGN KEY (org_id) REFERENCES tms_organizations(org_id),
  CONSTRAINT fk_nl_ticket FOREIGN KEY (ticket_id) REFERENCES tms_tickets(ticket_id)
);

CREATE TABLE tms_module_register (
  module_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  module_code VARCHAR2(100) NOT NULL UNIQUE,
  module_name VARCHAR2(200) NOT NULL,
  page_range_from NUMBER,
  page_range_to NUMBER,
  blueprint_version VARCHAR2(20) NOT NULL,
  uat_status VARCHAR2(30) DEFAULT 'NOT_STARTED' NOT NULL,
  created_by VARCHAR2(255) NOT NULL,
  created_date TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_by VARCHAR2(255),
  updated_date TIMESTAMP,
  record_version NUMBER DEFAULT 1 NOT NULL
);
