-- ============================================================
-- TMS Corrective Patch: Restore Profit Centre Hierarchy
-- Blueprint bump: v1.5 -> v1.6
-- Reference: locked decision in "Hierarchy And Authority Design"
--            (PROFIT CENTRE -> ORGANIZATION -> DEPARTMENT -> TICKET)
-- Run AFTER 01-09, against the existing TMS_OWNER schema.
-- ============================================================

-- 1. New table: TMS_PROFIT_CENTRES (global, not tenant-owned)
CREATE TABLE tms_profit_centres (
    profit_centre_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    profit_centre_code  VARCHAR2(30)  NOT NULL,
    profit_centre_name  VARCHAR2(200) NOT NULL,
    status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_by          VARCHAR2(100) DEFAULT USER NOT NULL,
    created_date        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_by          VARCHAR2(100),
    updated_date        TIMESTAMP,
    record_version      NUMBER DEFAULT 1 NOT NULL,
    CONSTRAINT pk_tms_profit_centres
        PRIMARY KEY (profit_centre_id),
    CONSTRAINT uk_tms_pc_code
        UNIQUE (profit_centre_code),
    CONSTRAINT ck_tms_pc_status
        CHECK (status IN ('ACTIVE','SUSPENDED','ONBOARDING'))
);

COMMENT ON TABLE tms_profit_centres IS
    'Structural parent of TMS_ORGANIZATIONS. One Profit Centre owns many Organizations. Global/system-level, not tenant-scoped.';

-- 2. Seed the Profit Centre that your existing TMS_SUPER row will attach to
INSERT INTO tms_profit_centres (profit_centre_code, profit_centre_name, status, created_by)
VALUES ('PC_SYSTEM', 'System / Default Profit Centre', 'ACTIVE', 'SYSTEM');

-- 3. Add the FK column to TMS_ORGANIZATIONS (nullable first, to backfill safely)
ALTER TABLE tms_organizations
    ADD profit_centre_id NUMBER;

-- 4. Backfill the existing seed row (TMS_SUPER...) against the new Profit Centre
UPDATE tms_organizations
   SET profit_centre_id = (SELECT profit_centre_id
                              FROM tms_profit_centres
                             WHERE profit_centre_code = 'PC_SYSTEM')
 WHERE profit_centre_id IS NULL;

COMMIT;

-- 5. Now enforce it: make the column mandatory and add the FK constraint
ALTER TABLE tms_organizations
    MODIFY profit_centre_id NOT NULL;

ALTER TABLE tms_organizations
    ADD CONSTRAINT fk_org_profit_centre
        FOREIGN KEY (profit_centre_id)
        REFERENCES tms_profit_centres(profit_centre_id);

-- 6. Extend the auth/data-access view to allow Profit-Centre-wide scope
--    (adjust to match your actual PKG_TMS_DATA_ACCESS.CAN_ACCESS_ORG signature)
CREATE OR REPLACE VIEW vw_tms_org_scope AS
SELECT o.org_id,
       o.org_code,
       o.org_name,
       o.parent_org_id,
       o.profit_centre_id,
       pc.profit_centre_code,
       pc.profit_centre_name
  FROM tms_organizations o
  JOIN tms_profit_centres pc
    ON pc.profit_centre_id = o.profit_centre_id;

COMMENT ON VIEW vw_tms_org_scope IS
    'Resolves each Organization to its owning Profit Centre. Use this to extend PKG_TMS_DATA_ACCESS for Profit-Centre-wide Super User scope.';

-- ============================================================
-- 7. COST CENTRE RECONCILIATION
-- ============================================================
-- Original locked decision: do NOT implement Cost Centre yet; keep it as
-- a future NVL(cost_centre_id, NULL) reporting placeholder only.
-- TMS_COST_CENTRES currently EXISTS as a real table in 02_security_and_
-- reference_tables.sql, ahead of that plan.
--
-- Two options -- pick ONE and run it. Do not run both.

-- OPTION A: Roll back to the original plan (drop the table; nothing
-- references it yet since it's outside the data-access engine).
-- Uncomment to use:
-- DROP TABLE tms_cost_centres CASCADE CONSTRAINTS;

-- OPTION B (recommended, less disruptive): keep the table, but formally
-- re-document it in the blueprint as an optional, deferred, non-hierarchical
-- classification -- exactly matching what 07_views.sql already enforces
-- ("TMS_COST_CENTRES is intentionally outside the data-access engine").
-- No SQL change needed for Option B -- it's a documentation correction only,
-- see the accompanying blueprint patch.

-- ============================================================
-- 8. Verification queries -- run after applying the above
-- ============================================================
-- SELECT * FROM tms_profit_centres;
-- SELECT org_id, org_code, org_name, profit_centre_id FROM tms_organizations;
-- SELECT * FROM vw_tms_org_scope;
